# Generated by Django 3.2.1 on 2021-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=200)),
                ('Assignment_Title', models.CharField(max_length=200)),
                ('Assignment_Description', models.CharField(max_length=200)),
                ('File_Name', models.CharField(max_length=200)),
                ('Assignment_File', models.CharField(max_length=200)),
                ('Submission_Date', models.CharField(max_length=200)),
            ],
        ),
    ]
