# Generated by Django 3.2.1 on 2021-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='File_Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
